from api.models import Product, Category, ProductCategory

def run():
    if len(Product.objects.all())==0 or len(Category.objects.all())==0 or len(ProductCategory.objects.all())==0:
        dota = Product.objects.create(name = 'dota2')
        dota.save()
        witcher = Product.objects.create(name = 'witcher')
        witcher.save()
        orange = Product.objects.create(name = 'orange')
        orange.save()
        mouse = Product.objects.create(name='mouse')
        mouse.save()
        hobbit = Product.objects.create(name='hobbit')
        hobbit.save()

        games = Category.objects.create(name='games')
        games.save()
        books = Category.objects.create(name='books')
        books.save()
        food = Category.objects.create(name='food')
        food.save()
        art = Category.objects.create(name='art')
        art.save()

        dota_game = ProductCategory.objects.create(product = dota, category = games)
        dota_game.save()
        witcher_game = ProductCategory.objects.create(product = witcher, category = games)
        witcher_game.save()
        hobbit_game = ProductCategory.objects.create(product = hobbit, category = games)
        hobbit_game.save()
        witcher_books = ProductCategory.objects.create(product = witcher, category = books)
        witcher_books.save()
        hobbit_books = ProductCategory.objects.create(product = hobbit, category = books)
        hobbit_books.save()
        orange_food = ProductCategory.objects.create(product = orange, category = food)
        orange_food.save()
